# Generated by Django 3.1.7 on 2021-04-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='PatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=150)),
                ('sex', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=350)),
                ('disease', models.CharField(max_length=150)),
                ('doctor', models.CharField(max_length=150)),
                ('drug', models.CharField(max_length=150)),
                ('drugstrength', models.CharField(max_length=150)),
                ('drugduration', models.CharField(max_length=150)),
                ('prescriptionadvice', models.CharField(max_length=150)),
                ('remarks', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
